### ISSUE TITLE
config/datasets folder is missing

### ISSUE THREAD

**Issue by Usama113** [ShichangZh/GStarX#1]
Hi, the config/datasets folder is missing. There are no yaml file available for datasets. Could you please provide them. Thanks in advance.

**Comment by ShichangZh** [comment]
Thanks for catching that. Previously I used regex to ignore everything with "datasets" to avoid pushing large files to GitHub. Now the folder is there, and please let me know if you have other questions.

**Comment by Usama113** [comment]
Yes, it is now there. Thanks a lot for your timely answer.
